'use strict';
const WebSocket = require('ws');
class SamsungClient {
  constructor(device, store, status = () => {}) { this.device = device; this.host = device.host; this.store = store; this.status = status; this.ws = null; }
  _urls() { const name = Buffer.from('Voltix Remote Studio').toString('base64'); const token = this.store.tokenFor(this.host); const q = token ? `&token=${encodeURIComponent(token)}` : ''; return [`wss://${this.host}:${this.device.securePort || 8002}/api/v2/channels/samsung.remote.control?name=${name}${q}`, `ws://${this.host}:${this.device.insecurePort || 8001}/api/v2/channels/samsung.remote.control?name=${name}${q}`]; }
  async connect() { let last; for (const url of this._urls()) { try { await this._connectUrl(url); this.status('connect', `Samsung connected at ${url.replace(/token=[^&]+/, 'token=<stored>')}`); return true; } catch (e) { last = e; this.status('connect', `Samsung connect failed: ${e.message}`); } } throw last || new Error('Samsung connection failed'); }
  _connectUrl(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url, { rejectUnauthorized: false, handshakeTimeout: 5000 }); const timer = setTimeout(() => reject(new Error('Samsung pairing timeout')), 12000); ws.on('open', () => { this.ws = ws; resolve(true); clearTimeout(timer); }); ws.on('message', raw => { try { const msg = JSON.parse(String(raw)); const token = msg?.data?.token; if (token) this.store.setToken(this.host, token); } catch (_) {} }); ws.on('error', err => { clearTimeout(timer); reject(err); }); }); }
  keyFor(cmd) { return { up:'KEY_UP', down:'KEY_DOWN', left:'KEY_LEFT', right:'KEY_RIGHT', ok:'KEY_ENTER', back:'KEY_RETURN', home:'KEY_HOME', info:'KEY_INFO', menu:'KEY_MENU', settings:'KEY_SETTINGS', volumeUp:'KEY_VOLUP', volumeDown:'KEY_VOLDOWN', mute:'KEY_MUTE', channelUp:'KEY_CHUP', channelDown:'KEY_CHDOWN', play:'KEY_PLAY', pause:'KEY_PAUSE', stop:'KEY_STOP', rewind:'KEY_REWIND', forward:'KEY_FF', powerOff:'KEY_POWER' }[cmd]; }
  async command(cmd) { const key = this.keyFor(cmd); if (!key) throw new Error(`Samsung command not mapped: ${cmd}`); if (!this.ws || this.ws.readyState !== WebSocket.OPEN) throw new Error('Samsung socket not connected'); this.ws.send(JSON.stringify({ method: 'ms.remote.control', params: { Cmd: 'Click', DataOfCmd: key, Option: 'false', TypeOfRemote: 'SendRemoteKey' } })); return { ok: true, key }; }
  async nowPlaying() { return { title: 'Samsung TV', subtitle: 'Samsung remote APIs do not expose universal show artwork', thumbnail: '', raw: {} }; }
  close() { try { if (this.ws) this.ws.close(); } catch (_) {} }
}
module.exports = { SamsungClient };
